/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Categories: typeof import('./.vitepress/theme/components/widget/Categories.vue')['default']
    Footer: typeof import('./.vitepress/theme/components/Footer.vue')['default']
    FooterLink: typeof import('./.vitepress/theme/components/FooterLink.vue')['default']
    HomePage: typeof import('./.vitepress/theme/components/HomePage.vue')['default']
    PostList: typeof import('./.vitepress/theme/components/PostList.vue')['default']
    Profile: typeof import('./.vitepress/theme/components/widget/Profile.vue')['default']
    Tags: typeof import('./.vitepress/theme/components/widget/Tags.vue')['default']
  }
}
