import type { SidebarsConfig } from '@docusaurus/plugin-content-docs'

const sidebars: SidebarsConfig = {
  knowledgeSidebar: [
    'intro',
    {
      type: 'category',
      label: 'JavaScript',
      items: [
        { type: 'autogenerated', dirName: 'javascript' },
      ],
    },
    {
      type: 'category',
      label: '读书笔记',
      // link: {
      //   type: 'generated-index',
      //   title: '读书笔记',
      //   slug: '/books/intro',
      // },
      items: [
        { type: 'autogenerated', dirName: 'books' },
      ],
    },
  ],

  columnsSidebar: [{ type: 'autogenerated', dirName: 'columns' }],
}

export default sidebars
